# Thesis Project

## Importing dataset and Preprocessing

In [1]:
import os
import pandas as pd

csv_directory = r'C:\Users\nicka\Downloads\mimic-iv-2.2\datasets'
csv_files = [file for file in os.listdir(csv_directory) if file.endswith('.csv')]

csv_file_path = os.path.join(csv_directory, 'icustays.csv')
icustays_df = pd.read_csv(csv_file_path)
icustays_df

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10000032,29079034,39553978,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2180-07-23 14:00:00,2180-07-23 23:50:47,0.410266
1,10000980,26913865,39765666,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2189-06-27 08:42:00,2189-06-27 20:38:27,0.497535
2,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032
3,10001217,27703517,34592300,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-12-19 15:42:24,2157-12-20 14:27:41,0.948113
4,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588
...,...,...,...,...,...,...,...,...
73176,19999442,26785317,32336619,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2148-11-19 14:23:43,2148-11-26 13:12:15,6.950370
73177,19999625,25304202,31070865,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2139-10-10 19:18:00,2139-10-11 18:21:28,0.960741
73178,19999828,25744818,36075953,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2149-01-08 18:12:00,2149-01-10 13:11:02,1.790995
73179,19999840,21033226,38978960,Trauma SICU (TSICU),Surgical Intensive Care Unit (SICU),2164-09-12 09:26:28,2164-09-17 16:35:15,5.297766
73180,19999987,23865745,36195440,Trauma SICU (TSICU),Trauma SICU (TSICU),2145-11-02 22:59:00,2145-11-04 21:29:30,1.937847

In [2]:
csv_file_path = os.path.join(csv_directory, 'admissions.csv')
admissions_df = pd.read_csv(csv_file_path)
admissions_df

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
0,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P874LG,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0
1,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P09Q6Y,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0
2,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P60CC5,EMERGENCY ROOM,HOSPICE,Medicaid,ENGLISH,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0
3,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P30KEH,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0
4,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,NaN,EU OBSERVATION,P51VDL,EMERGENCY ROOM,NaN,Other,ENGLISH,SINGLE,WHITE,2160-03-03 21:55:00,2160-03-04 06:26:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
431226,19999828,25744818,2149-01-08 16:44:00,2149-01-18 17:00:00,NaN,EW EMER.,P75BG6,TRANSFER FROM HOSPITAL,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE,2149-01-08 09:11:00,2149-01-08 18:12:00,0
431227,19999828,29734428,2147-07-18 16:23:00,2147-08-04 18:10:00,NaN,EW EMER.,P16C7J,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,ENGLISH,SINGLE,WHITE,2147-07-17 17:18:00,2147-07-18 17:34:00,0
431228,19999840,21033226,2164-09-10 13:47:00,2164-09-17 13:42:00,2164-09-17 13:42:00,EW EMER.,P58A9J,EMERGENCY ROOM,DIED,Other,ENGLISH,WIDOWED,WHITE,2164-09-10 11:09:00,2164-09-10 14:46:00,1
431229,19999840,26071774,2164-07-25 00:27:00,2164-07-28 12:15:00,NaN,EW EMER.,P506DE,EMERGENCY ROOM,HOME,Other,ENGLISH,WIDOWED,WHITE,2164-07-24 21:16:00,2164-07-25 01:20:00,0
431230,19999987,23865745,2145-11-02 21:38:00,2145-11-11 12:57:00,NaN,EW EMER.,P09IS0,EMERGENCY ROOM,REHAB,Other,ENGLISH,NaN,UNKNOWN,2145-11-02 19:28:00,2145-11-02 22:59:00,0

In [3]:
csv_file_path = os.path.join(csv_directory, 'patients.csv')
patients_df = pd.read_csv(csv_file_path)
patients_df

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
0,10000032,F,52,2180,2014 - 2016,2180-09-09
1,10000048,F,23,2126,2008 - 2010,NaN
2,10000068,F,19,2160,2008 - 2010,NaN
3,10000084,M,72,2160,2017 - 2019,2161-02-13
4,10000102,F,27,2136,2008 - 2010,NaN
...,...,...,...,...,...,...
299707,19999828,F,46,2147,2017 - 2019,NaN
299708,19999829,F,28,2186,2008 - 2010,NaN
299709,19999840,M,58,2164,2008 - 2010,2164-09-17
299710,19999914,F,49,2158,2017 - 2019,NaN
299711,19999987,F,57,2145,2011 - 2013,NaN

In [4]:
assert set(icustays_df['hadm_id']).issubset(set(admissions_df['hadm_id']))

def dataframe_datetime(df) :
    
    for c in [c for c in df.columns if 'time' in c] :

        try :
            df[c] = pd.to_datetime(df[c])
        except Exception :
            pass

    return df

import pandas as pd
import gc

icustays_df = dataframe_datetime(icustays_df)
admissions_df = dataframe_datetime(admissions_df)

In [5]:
import numpy as np 

# Keep icustays with lengths of stay greater or equal to 1 day
icustays_df = icustays_df[icustays_df['los'] >= 1]
icu_hadm_ids = set(icustays_df['hadm_id']) & set(admissions_df['hadm_id'])
admissions_df = admissions_df[admissions_df['hadm_id'].isin(icu_hadm_ids)]
subjects = set(admissions_df['subject_id'])
stays = set(icustays_df['stay_id'])

In [6]:
#Here the variable age is defined
patients_df = patients_df[patients_df['subject_id'].isin(subjects)]
patients_df['gender'] = np.array(patients_df['gender'] == 'F').astype(int)
anchor_age_tuples = patients_df.apply(lambda row : (row['subject_id'], row['anchor_age'], row['anchor_year']), 1)
anchor_age_dict = {subject_id:{'anchor_age':anchor_age, 'anchor_year':anchor_year} for subject_id,anchor_age,anchor_year in anchor_age_tuples}
gender_dict = dict(zip(patients_df['subject_id'], patients_df['gender']))
icustays_df['age'] = icustays_df.apply(lambda row : anchor_age_dict[row['subject_id']]['anchor_age'] + (row['intime'].year - anchor_age_dict[row['subject_id']]['anchor_year']), 1)
icustays_df['age'] = icustays_df.apply(lambda row : row['age'] if row['age'] <= 90 else 90, 1) # HIPAA deidentification rule
icustays_df['gender'] = icustays_df.apply(lambda row: gender_dict[row['subject_id']], 1)

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\2300238789.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  patients_df['gender'] = np.array(patients_df['gender'] == 'F').astype(int)
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\2300238789.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  icustays_df['age'] = icustays_df.apply(lambda row : anchor_age_dict[row['subject_id']]['anchor_age'] + (row['intime'].year - anchor_age_dict[row['subject_id']]['anchor_year']), 1)
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\2300238789.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  icustays_df['age'] = icustays_df.apply(lambda row : row['age'] if row['age'] <= 90 else 90, 1) # HIPAA deidentification rule
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\2300238789.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  icustays_df['gender'] = icustays_df.apply(lambda row: gender_dict[row['subject_id']], 1)

In [7]:
admissions_df = admissions_df[admissions_df['subject_id'].isin(subjects)]
insurance_dict = dict(zip(admissions_df['subject_id'], admissions_df['insurance']))
icustays_df['insurance'] = icustays_df['subject_id'].map(insurance_dict)
admloc_dict = dict(zip(admissions_df['subject_id'], admissions_df['admission_location']))
icustays_df['admission location'] = icustays_df['subject_id'].map(admloc_dict)
race_dict = dict(zip(admissions_df['subject_id'], admissions_df['race']))
icustays_df['race'] = icustays_df['subject_id'].map(race_dict)

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\1110605474.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  icustays_df['insurance'] = icustays_df['subject_id'].map(insurance_dict)
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\1110605474.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  icustays_df['admission location'] = icustays_df['subject_id'].map(admloc_dict)
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\1110605474.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  icustays_df['race'] = icustays_df['subject_id'].map(race_dict)

In [8]:
import pandas as pd
import os

csv_directory = r'C:\Users\nicka\Downloads\mimic-iv-2.2\datasets'

# Read d_items.csv and filter for routine vital signs
csv_file_path = os.path.join(csv_directory, 'd_items.csv')
chartevent_definitions = pd.read_csv(csv_file_path, low_memory=True)
chartevent_definitions = chartevent_definitions[
    (chartevent_definitions['linksto'] == 'chartevents') & 
    (chartevent_definitions['category'] == 'Routine Vital Signs')
]
routine_vital_items = chartevent_definitions['itemid'].values

stays = set(icustays_df['stay_id'])
subjects = set(icustays_df['subject_id'])

for p in [os.path.join('.', 'data'), os.path.join('.', 'data', 'mimic_chartevents')]:
    if not os.path.isdir(p):
        os.mkdir(p)

mimic_chartevents_parent = os.path.join('.', 'data', 'mimic_chartevents')

# Read chartevents.csv in chunks and filter
if len(os.listdir(mimic_chartevents_parent)) == 0:
    csv_file_path = os.path.join(csv_directory, 'chartevents.csv')
    chartevents = pd.read_csv(csv_file_path, chunksize=10000000)
    
    for i, chunk in enumerate(chartevents):
        original_size = chunk.shape
        chunk = chunk[
            (chunk['stay_id'].isin(stays)) & 
            (chunk['itemid'].isin(routine_vital_items))
        ]
        chunk.to_csv(os.path.join(mimic_chartevents_parent, f'mimic_vitals_{i}.csv'), index=False)
        print(f'Chunk {i}: selected {chunk.shape[0]} from {original_size[0]} rows.')

def get_files_of_type(directory, filetype='csv'):
    return [os.path.join(directory, file) for file in os.listdir(directory) if file.endswith(f'.{filetype}')]

chartevents_df = pd.concat(
    [pd.read_csv(path) for path in get_files_of_type(mimic_chartevents_parent, filetype='csv')], 
    axis=0, 
    ignore_index=True
)
chartevents_df.reset_index(drop=True, inplace=True)
chartevents_df['charttime'] = pd.to_datetime(chartevents_df['charttime'])
filtered_chartevents_df = chartevents_df.groupby(['stay_id', 'itemid']).first().reset_index()

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\2220658790.py:41: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  chartevents_df = pd.concat(

In [9]:
filtered_chartevents_df = pd.merge(
    filtered_chartevents_df,
    icustays_df,
    how='inner',
    on=['stay_id','subject_id','hadm_id']
)

In [10]:
def dataframe_datetime(df):
    datetime_columns = ['charttime', 'storetime']
    for col in datetime_columns:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce')
    return df

csv_directory = r'C:\Users\nicka\Downloads\mimic-iv-2.2\datasets'

subjects = set(icustays_df['subject_id'])

filtered_labevents_dir = os.path.join('.', 'data', 'mimic_labevents')
if not os.path.isdir(filtered_labevents_dir):
    os.makedirs(filtered_labevents_dir)

# Read labevents.csv in chunks and filter
csv_file_path = os.path.join(csv_directory, 'labevents.csv')
chunks = []
chunk_size = 10000000  # Adjust as needed

for i, chunk in enumerate(pd.read_csv(csv_file_path, chunksize=chunk_size, low_memory=True)):
    original_size = chunk.shape
    chunk = chunk[chunk['subject_id'].isin(subjects)]
    chunk = dataframe_datetime(chunk)
    chunk.to_csv(os.path.join(filtered_labevents_dir, f'filtered_labevents_{i}.csv'), index=False)
    print(f'Chunk {i}: selected {chunk.shape[0]} from {original_size[0]} rows.')
    chunks.append(chunk)

labevents_df = pd.concat(chunks, axis=0, ignore_index=True)
labevents_df.reset_index(drop=True, inplace=True)

filtered_labs_df = pd.merge(
    labevents_df,
    icustays_df,
    how='inner',
    left_on=['subject_id', 'hadm_id'],
    right_on=['subject_id', 'hadm_id']
)

filtered_labs_df['charttime'] = pd.to_datetime(filtered_labs_df['charttime'])

condition = (filtered_labs_df['charttime'] >= filtered_labs_df['intime']) & (filtered_labs_df['charttime'] <= filtered_labs_df['outtime'])
filtered_labs_df.loc[condition, 'stay_id'] = filtered_labs_df.loc[condition, 'stay_id']

filtered_labs_df['value'] = pd.to_numeric(filtered_labs_df['value'], errors='coerce')
duplicates_for_stay_id = filtered_labs_df[filtered_labs_df.duplicated(subset=['stay_id', 'itemid'], keep=False)]
averages_for_duplicates = duplicates_for_stay_id.groupby(['stay_id', 'itemid'])['value'].mean().reset_index()
filtered_labs_df = pd.merge(filtered_labs_df, averages_for_duplicates, how='left', on=['stay_id', 'itemid'], suffixes=('', '_avg'))
filtered_labs_df['value'].fillna(filtered_labs_df['value_avg'], inplace=True)
filtered_labs_df.drop(columns=['value_avg'], inplace=True)

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 0: selected 4576020 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 1: selected 4652187 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 2: selected 4660421 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 3: selected 4604493 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 4: selected 4737221 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 5: selected 4595248 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 6: selected 4701625 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 7: selected 4544621 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 8: selected 4558158 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 9: selected 4720302 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 10: selected 4533842 from 10000000 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = pd.to_datetime(df[col], errors='coerce')

Chunk 11: selected 3869123 from 8171367 rows.

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\267303021.py:49: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  filtered_labs_df['value'].fillna(filtered_labs_df['value_avg'], inplace=True)

In [11]:
# Read perscriptions.csv and filter for routine vital signs
csv_file_path = os.path.join(csv_directory, 'prescriptions.csv')
pharm_df = pd.read_csv(csv_file_path, low_memory=True)
filtered_pharm_df = pd.merge(
    pharm_df,
    icustays_df,
    how='inner',
    left_on=['subject_id', 'hadm_id'],
    right_on=['subject_id', 'hadm_id']
)

filtered_pharm_df['starttime'] = pd.to_datetime(filtered_pharm_df['starttime'])
condition = (filtered_pharm_df['starttime'] >= filtered_pharm_df['intime']) & (filtered_pharm_df['starttime'] <= filtered_pharm_df['outtime'])
filtered_pharm_df.loc[condition, 'stay_id'] = filtered_pharm_df.loc[condition, 'stay_id']

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\1524235634.py:3: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  pharm_df = pd.read_csv(csv_file_path, low_memory=True)

In [12]:
analysis_chartevents_df = filtered_chartevents_df[['stay_id', 'subject_id', 'itemid', 'valuenum','insurance','gender','age','race']]
analysis_labs_df = filtered_labs_df[['subject_id', 'stay_id', 'itemid', 'value','insurance','gender','age','race']]
analysis_pharm_df = filtered_pharm_df[['subject_id', 'stay_id', 'drug','insurance','gender','age','race']]
_chartevents_df = filtered_chartevents_df[['stay_id', 'subject_id', 'itemid', 'valuenum']]
_labs_df = filtered_labs_df[['subject_id', 'stay_id', 'itemid', 'value']]
_pharm_df = filtered_pharm_df[['subject_id', 'stay_id', 'drug']]
csv_file_path = os.path.join(csv_directory, 'd_items.csv')
d_items = pd.read_csv(csv_file_path,low_memory=True)
itemid_to_label = d_items.set_index('itemid')['label'].to_dict()
_chartevents_df['itemid'] = _chartevents_df['itemid'].map(itemid_to_label)
csv_file_path = os.path.join(csv_directory, 'd_labitems.csv')
d_labitems = pd.read_csv(csv_file_path,low_memory=True)
itemid_to_label = d_labitems.set_index('itemid')['label'].to_dict()
_labs_df['itemid'] = _labs_df['itemid'].map(itemid_to_label)

final_chartevents = _chartevents_df.pivot_table(
    index=['subject_id', 'stay_id'],
    columns='itemid',
    values='valuenum',
    fill_value=0  
)
final_chartevents = final_chartevents.reset_index()

_labs_df['value'] = pd.to_numeric(_labs_df['value'], errors='coerce')
final_labs = _labs_df.pivot_table(
    index=['subject_id', 'stay_id'],
    columns='itemid',
    values='value',
    fill_value=0  
)
final_labs = final_labs.reset_index()

_pharm_df['value'] = 1
final_pharm = _pharm_df.pivot_table(index=['subject_id', 'stay_id'], columns='drug', values='value', fill_value=0)
final_pharm = final_pharm.reset_index()

C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\704570249.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  _chartevents_df['itemid'] = _chartevents_df['itemid'].map(itemid_to_label)
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\704570249.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  _labs_df['itemid'] = _labs_df['itemid'].map(itemid_to_label)
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\704570249.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  _labs_df['value'] = pd.to_numeric(_labs_df['value'], errors='coerce')
C:\Users\nicka\AppData\Local\Temp\ipykernel_20148\704570249.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  _pharm_df['value'] = 1

In [13]:
admissions_df['deathtime'] = np.where(admissions_df['deathtime'].isna(), 0, 1)
df_selected = admissions_df.loc[:, ['subject_id', 'hadm_id', 'deathtime']]

# Merge the first two pivoted DataFrames
icu_data_test = pd.merge(icustays_df, final_chartevents, on=['subject_id', 'stay_id'], how='inner')

# Merge the third pivoted DataFrame
icu_data_test = pd.merge(icu_data_test, final_labs, on=['subject_id', 'stay_id'], how='inner')

# Merge the icustays_df DataFrame
icu_data_test = pd.merge(icu_data_test, final_pharm, on=['subject_id', 'stay_id'], how='inner')

icu_data_test = pd.merge(icu_data_test, df_selected, on=['subject_id', 'hadm_id'], how='inner')

# Display the resulting DataFrame
icu_data_test.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los,age,gender,...,zanamivir,zeas,zileuton,zinc oxide,zinc oxide-white petrolatum,zolmitriptan,zonisamide,zydis,zz,deathtime
0,10001217,24597018,37067082,Surgical Intensive Care Unit (SICU),Surgical Intensive Care Unit (SICU),2157-11-20 19:18:02,2157-11-21 22:08:00,1.118032,55,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,10001725,25563031,31205490,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2110-04-11 15:52:22,2110-04-12 23:59:56,1.338588,46,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,10001884,26184834,37510196,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2131-01-11 04:20:05,2131-01-20 08:27:30,9.171817,77,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
3,10002013,23581541,39060235,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),2160-05-18 10:00:53,2160-05-19 17:33:33,1.314352,57,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,10002155,23822395,33685454,Coronary Care Unit (CCU),Coronary Care Unit (CCU),2129-08-04 12:45:00,2129-08-10 17:02:38,6.178912,81,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [14]:
# Mapping dictionary for race renaming
race_mapping = {
    'ASIAN - ASIAN INDIAN': 'ASIAN',
    'ASIAN - CHINESE': 'ASIAN',
    'ASIAN - KOREAN': 'ASIAN',
    'ASIAN - SOUTH EAST ASIAN': 'ASIAN',
    'UNKNOWN': 'OTHER',
    'UNABLE TO OBTAIN': 'OTHER',
    'PATIENT DECLINED TO ANSWER': 'OTHER',
    'WHITE - RUSSIAN': 'WHITE',
    'PORTUGUESE': 'WHITE',
    'WHITE - BRAZILIAN': 'WHITE',
    'WHITE - OTHER EUROPEAN': 'WHITE',
    'WHITE - EASTERN EUROPEAN': 'WHITE', 
    'BLACK/CAPE VERDEAN':'BLACK/AFRICAN AMERICAN',
    'BLACK/AFRICAN':'BLACK/AFRICAN AMERICAN',
    'BLACK/CARIBBEAN ISLAND':'BLACK/AFRICAN AMERICAN',
    'HISPANIC/LATINO - CUBAN': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - PUERTO RICAN': 'HISPANIC/LATINO',
    'HISPANIC OR LATINO': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - SALVADORAN': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - DOMINICAN': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - HONDURAN': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - COLUMBIAN': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - GUATEMALAN': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - CENTRAL AMERICAN': 'HISPANIC/LATINO',
    'HISPANIC/LATINO - MEXICAN': 'HISPANIC/LATINO',
    'SOUTH AMERICAN': 'HISPANIC/LATINO',
    'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER': 'OTHER',
    'AMERICAN INDIAN/ALASKA NATIVE': 'OTHER',
    'NATIVE HAWAIIAN/PACIFIC ISLANDER': 'OTHER',
    'MULTIPLE RACE/ETHNICITY': 'OTHER',
    'PACIFIC ISLANDER': 'OTHER'
    
}

icu_data_test['race'] = icu_data_test['race'].replace(race_mapping)
icu_data_test = icu_data_test.drop_duplicates(subset='subject_id', keep='last')
icu_data_test['gender'] = icu_data_test['gender'].map({0: 'Male', 1: 'Female'})